using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ShurikkenMovement : MonoBehaviour
{
    
    EnemyMovement enemyMovemnt;
    playerHealth playerHealth;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    private void OnCollisionEnter2D(Collision2D other)
    {   
        float da単o;
        if(enemyMovemnt.TypeAttack == 1){
            da単o = UnityEngine.Random.Range(0.01f, 0.03f);
        }else{
            da単o = 0;
        }

        if(other.gameObject.CompareTag("Player"))
        {
            playerHealth.health -= da単o;
            Debug.Log("Vida Jugador: " + playerHealth.health);
        }
    }
}
